name: CadiaCore2
author: crus3r
version: 2.0
main: me.crus3r.cadiacore2.CadiaCore2
description: Core Plugin written in Java by Sam Taber (crus3r)
commands:
  fly:
    description: Enables/Disables Flight for a/the player.
  heal:
    description: Heals a/the player.
  hat:
    description: Sets a players hat.
  tp:
    description: Teleports a player to a target player.
  workbench:
    description: Opens up a portable workbench.
  enderchest:
    description: Opens up a player's ender chest.
    aliases: [ec, ender]
  feed:
    description: Feeds a/the player.
  broadcast:
    description: Broadcasts a message.
    aliases: [shout]
  vanish:
    description: Vanishs a player.
    aliases: [v]
  gamemode:
    aliases: [gm]
    description: Change your gamemode.
  helpss:
    description: meow